In [67]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from mlxtend.classifier import StackingClassifier

In [68]:
data0 = load_wine()
data1 = pd.DataFrame(data= np.c_[data0['data'], data0['target']],columns= data0['feature_names'] + ['target'])
data1['target'] = data1['target'].replace([0., 1., 2.],[0,1,1])
#data1.target.unique()

In [69]:
y = data1['target'].copy()
X = data1.drop(['target'],axis=1)

In [70]:
# Normalizing the data sets Creating the scaling function
minmaxScaler = preprocessing.MinMaxScaler()
# Transforming with the scaler function
X_tran = pd.DataFrame(minmaxScaler.fit_transform(X))

In [71]:
# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_tran, y, test_size=0.3,random_state=123)

# Ensemble Model Using the Averaging Technique

In [72]:
def average_ensemble_modeling(X_train,y_train,X_test,*models):
    prediction0=np.zeros(shape=(len(X_test),2),dtype='float') 
    for model in models:
        model.fit(X_train,y_train)
        pred=model.predict_proba(X_test)
        prediction0=prediction0+pred
    return prediction0/3

In [73]:
ensemblepred=average_ensemble_modeling(X_train,y_train,X_test,model1,model2,model3)
pred = np.argmax(ensemblepred,axis = 1)
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

[[14  0]
 [ 0 40]]


# Ensemble Model Using Max Voting

In [74]:
model = VotingClassifier(estimators=[('lr', model1),('knn', model2),('rf', model3)],voting= 'hard')

In [75]:
model.fit(X_train,y_train)
model.score(X_test,y_test)
preds = model.predict(X_test)
print('Confusion Matrix \n',confusion_matrix(y_test, preds))
print('Classification report \n',classification_report(y_test, preds))


Confusion Matrix 
 [[14  0]
 [ 0 40]]
Classification report 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        14
         1.0       1.00      1.00      1.00        40

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



# Ensemble Learning Using Bagging

In [76]:
bl1 = RandomForestClassifier(random_state=123)

In [77]:
baggingLearner = BaggingClassifier(base_estimator=bl1, n_estimators=10, max_samples=0.8, max_features=0.7)

In [78]:
# Fitting the model using the meta learner
model = baggingLearner.fit(X_train, y_train)
# Predicting on the test set using the model
pred = model.predict(X_test)
print('Confusion Matrix \n',confusion_matrix(y_test, preds))
print('Classification report \n',classification_report(y_test, preds))



Confusion Matrix 
 [[14  0]
 [ 0 40]]
Classification report 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        14
         1.0       1.00      1.00      1.00        40

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



# Ensemble Learning Using Boosting

In [79]:
bl1 = LogisticRegression(random_state=123)

In [80]:
boosting = AdaBoostClassifier(base_estimator=bl1,n_estimators=200)

In [81]:
# Fitting the model on the training set
model = boosting.fit(X_train, y_train)
# Getting the predictions from the boosting model
pred = model.predict(X_test)
print('Confusion Matrix \n',confusion_matrix(y_test, preds))
print('Classification report \n',classification_report(y_test, preds))



Confusion Matrix 
 [[14  0]
 [ 0 40]]
Classification report 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        14
         1.0       1.00      1.00      1.00        40

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



# Ensemble Learning Using Stacking

In [82]:
bl1 = KNeighborsClassifier(n_neighbors=5)
bl2 = RandomForestClassifier(random_state=123)
ml = LogisticRegression(random_state=123)


In [83]:
stackclf = StackingClassifier(classifiers=[bl1, bl2],meta_classifier=ml)

In [84]:
# Fitting the model on the training set
model = stackclf.fit(X_train, y_train)
# Generating predictions on test set
pred = model.predict(X_test)
print('Confusion Matrix \n',confusion_matrix(y_test, preds))
print('Classification report \n',classification_report(y_test, preds))


Confusion Matrix 
 [[14  0]
 [ 0 40]]
Classification report 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        14
         1.0       1.00      1.00      1.00        40

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54

